apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 884634136969.dkr.ecr.us-east-1.amazonaws.com/openpament
  newName: 884634136969.dkr.ecr.us-east-1.amazonaws.com/openpament
  newTag: 6a905de6ee86cfa1ebdb1d95002e218688f41067
resources:
- ../../base
patchesStrategicMerge:
- ecr-demo-patch.yaml
- ecr-service-patch.yaml
