---
apiVersion: v1
kind: Service
metadata:
  name: ecr-demo
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthy
spec:
  selector:
    app: ecr-demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
